# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec -- one double-clickable Windows .exe.

    .venv\\Scripts\\python.exe -m PyInstaller sj-mosquito-maps.spec --noconfirm
    (or just run build-exe.cmd)

WHAT SHIPS INSIDE THE EXE
-------------------------
  index.html          the entire frontend, at the bundle root
  data/*.json         the seed archive: 863 operations, 316 shapes, ~1.4 MB
  data/*.geojson

The seed archive is the reason this build is worth doing at all. `data/` is
committed because it IS the archive -- the district's page keeps only ~2 months
and an entry that rolls off cannot be re-fetched from anywhere. Shipping it
inside the exe means a fresh install opens instantly, works with no network,
and never needs a first-run download that could fail.

Everything in the bundle is READ-ONLY and, for a onefile build, EPHEMERAL: the
bootloader unpacks it to sys._MEIPASS and deletes that directory on exit.
sjmvcd/paths.py owns that distinction -- bundle_dir() for these files,
data_dir() (%LOCALAPPDATA%/sj-mosquito-maps/data) for anything written -- and
seed_data_dir() copies this bundled archive out to the writable side on first
run, never overwriting a file the user already has. Nothing in this spec may
assume the two directories are the same place.

WHY THERE IS NO CONSOLE, AND WHY THAT IS STILL DEBUGGABLE
---------------------------------------------------------
console=False, because a GUI app that flashes a black terminal looks broken to
the person this build is for. The cost of a windowed build is that sys.stdout
and sys.stderr are None, so an exception during startup kills the process with
no window, no message, and no trace -- the single worst failure mode to hand a
non-developer. The runtime hook generated below reconnects both streams to a
log file under %LOCALAPPDATA%/sj-mosquito-maps/logs/ and pops a message box
naming that file if the app dies. See _RUNTIME_HOOK_SOURCE.
"""

from pathlib import Path

from PyInstaller.utils.hooks import collect_submodules

ROOT = Path(SPECPATH).resolve()          # SPECPATH is injected by PyInstaller
APP_NAME = "sj-mosquito-maps"


# -----------------------------------------------------------------------------
# Bundled (read-only) payload
# -----------------------------------------------------------------------------
def seed_payload():
    """
    (source, dest) pairs for the frontend and the seed archive.

    data/ is walked rather than globbed wholesale so that data/.cache/ -- raw
    archived HTML, gitignored, regenerable, and several times the size of the
    archive itself -- never lands in the installer. Dotfiles are skipped for
    the same reason. The layout mirrors the repo exactly (index.html at the
    root, archive under data/), because sjmvcd.paths.seed_data_dir() looks for
    bundle_dir()/"data" and app.py serves the frontend from bundle_dir().
    """
    payload = [(str(ROOT / "index.html"), ".")]

    # Vendored Leaflet. Without this the exe ships 1.3 MB of archive and then
    # cannot draw any of it without reaching unpkg.com -- the "works offline"
    # promise would be false at the first launch on a plane or a locked-down
    # network. Basemap TILES still need the network; the polygons no longer do.
    vendor_dir = ROOT / "vendor"
    vendored = 0
    for entry in sorted(vendor_dir.rglob("*")):
        if not entry.is_file():
            continue
        # Preserve the tree: leaflet.css references images/ by relative path.
        payload.append((str(entry), str(Path("vendor") / entry.parent.relative_to(vendor_dir))))
        vendored += 1
    if vendored == 0:
        raise SystemExit(
            f"{APP_NAME}.spec: vendor/ is empty. index.html loads Leaflet from "
            "there, so the exe would build and then show no map at all."
        )

    data_dir = ROOT / "data"
    seeded = 0
    for entry in sorted(data_dir.iterdir()):
        if not entry.is_file() or entry.name.startswith("."):
            continue
        payload.append((str(entry), "data"))
        seeded += 1

    # A build that silently shipped an empty archive would look fine and then
    # show an empty map, so make the omission loud at build time instead.
    if seeded == 0:
        raise SystemExit(
            f"{APP_NAME}.spec: no seed data found in {data_dir}. "
            "Run `python fetch_data.py` before building, or the exe ships an empty map."
        )
    return payload


# -----------------------------------------------------------------------------
# Runtime hook: give a windowed build a voice
# -----------------------------------------------------------------------------
# Written to build/ rather than kept as a checked-in file so the repo keeps one
# build definition in one place; it is pure build output and is regenerated on
# every run. It executes inside the frozen app BEFORE app.py, which is exactly
# when an import error or a missing DLL would otherwise kill us silently.
_RUNTIME_HOOK_SOURCE = r'''
"""
GENERATED by sj-mosquito-maps.spec -- do not edit; edit the spec.

A windowed PyInstaller build has no console, so sys.stdout/sys.stderr are None
and every print(), every http.server access log, and every unhandled traceback
goes nowhere. This hook points all of it at a log file next to the writable
archive, and turns a silent death into a message box that names the file.
"""

import os
import sys
import tempfile
from pathlib import Path

_MAX_BYTES = 512 * 1024      # one truncation, no rotation scheme to maintain
_APP_NAME = "sj-mosquito-maps"
_TITLE = "San Joaquin County spray timelapse"


def _log_dir():
    """
    Always <user app data>/sj-mosquito-maps/logs, never derived from the archive.

    Deriving it from data_dir().parent looked tidier but followed
    $SJMVCD_DATA_DIR wherever it pointed: with the archive overridden to a temp
    folder, the app created a bare logs/ directory directly inside %TEMP%,
    outside its own namespace entirely. The log belongs to the application, not
    to whichever archive it happens to be showing, so it is anchored to the
    app-data root on its own. verify_data.py and the archive-merge code have
    opinions about what lives in data/, and a log file is not one of them.
    """
    try:
        from sjmvcd.paths import _user_data_root
        base = _user_data_root() / _APP_NAME / "logs"
    except Exception:
        local = os.environ.get("LOCALAPPDATA")
        base = (Path(local) if local else Path.home()) / _APP_NAME / "logs"
    try:
        base.mkdir(parents=True, exist_ok=True)
        return base
    except Exception:
        return Path(tempfile.gettempdir())


def _open_log():
    path = _log_dir() / (_APP_NAME + ".log")
    try:
        if path.is_file() and path.stat().st_size > _MAX_BYTES:
            path.write_text("", encoding="utf-8")
    except OSError:
        pass
    # Line buffered: a crash must not eat the line that explains it.
    return path, open(path, "a", encoding="utf-8", errors="replace", buffering=1)


try:
    _LOG_PATH, _LOG = _open_log()
except Exception:
    _LOG_PATH, _LOG = None, None

if _LOG is not None:
    sys.stdout = _LOG
    sys.stderr = _LOG

    try:
        import faulthandler
        faulthandler.enable(_LOG)     # catches interpreter-level hard crashes
    except Exception:
        pass

    try:
        import datetime
        _LOG.write("\n=== %s  start (pid %d) ===\n"
                   % (datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), os.getpid()))
        from sjmvcd.paths import describe
        _LOG.write(describe() + "\n")
    except Exception:
        pass

    def _excepthook(exc_type, exc, tb):
        import traceback
        traceback.print_exception(exc_type, exc, tb, file=_LOG)
        try:
            _LOG.flush()
        except Exception:
            pass
        if sys.platform == "win32" and not issubclass(exc_type, KeyboardInterrupt):
            try:
                import ctypes
                ctypes.windll.user32.MessageBoxW(
                    None,
                    "%s could not start.\n\n%s: %s\n\nDetails were written to:\n%s"
                    % (_TITLE, exc_type.__name__, exc, _LOG_PATH),
                    _TITLE,
                    0x10,            # MB_ICONERROR
                )
            except Exception:
                pass

    sys.excepthook = _excepthook
'''

_hook_dir = ROOT / "build" / "runtime-hooks"
_hook_dir.mkdir(parents=True, exist_ok=True)
_hook_path = _hook_dir / "rth_windowed_logging.py"
_hook_path.write_text(_RUNTIME_HOOK_SOURCE, encoding="utf-8")


# -----------------------------------------------------------------------------
# Hidden imports -- what static analysis provably cannot see
# -----------------------------------------------------------------------------
# Kept deliberately short. Every entry below was checked against the installed
# packages rather than copied from a forum post; things PyInstaller's bundled
# hooks already handle are named here only as comments.
#
#   certifi        NOT listed: hook-certifi.py (hooks-contrib) collects the CA
#                  bundle, and requests imports certifi statically anyway.
#   pythonnet/clr  NOT listed: hook-clr.py adds Python.Runtime.dll plus its
#                  internal imports; `import clr` in winforms.py is static.
#   webview libs   NOT listed: hook-webview.py collects webview/lib (the
#                  WebView2 interop DLLs) and the dynamic libraries.
#   bs4 parser     NOT listed: bs4/builder/__init__.py imports _htmlparser at
#                  module scope (line 832), so it is followed statically. The
#                  *selection* is lazy; the import is not.
HIDDEN_IMPORTS = [
    # pywebview picks its backend at runtime in guilib.py by calling
    # import_winforms() etc. Those imports live inside functions wrapped in
    # try/except, so a hook or analysis change that stops following them would
    # degrade the app to "browser fallback" with no error anyone would notice.
    # Naming them keeps the native window a build-time guarantee.
    "webview.platforms.winforms",
    "webview.platforms.edgechromium",   # the WebView2 renderer, the normal path
    "webview.platforms.mshtml",         # legacy fallback when WebView2 is absent
    "webview.platforms.win32",

    # The refresh path. The refresh runs IN-PROCESS -- shelling out cannot work
    # when frozen, because sys.executable is this GUI exe and there is no .py
    # file on disk -- so the fetcher and its dependency tree have to be in the
    # bundle. serve.py and app.py both import it at module scope, but naming it
    # here keeps that a build-time guarantee rather than something a future
    # refactor to a lazy import could quietly break.
    #
    # verify_data is deliberately NOT listed. Nothing in the frozen app calls
    # it, so bundling it only added dead weight behind a comment claiming it
    # was part of this path. If a "check my archive" action is ever added to
    # the UI, add it back with the code that uses it.
    "fetch_data",
] + collect_submodules("sjmvcd")   # incl. sjmvcd.paths -- the frozen/dev router


# -----------------------------------------------------------------------------
# Dead weight
# -----------------------------------------------------------------------------
# This app is HTTP + HTML + a system webview. It has no GUI toolkit of its own,
# no plotting, no notebooks. Most of these are belt-and-braces (nothing imports
# them today) but they are the packages that get pulled in by accident when a
# dependency grows an optional feature, and each one is megabytes.
EXCLUDES = [
    "tkinter", "_tkinter", "turtle", "turtledemo", "idlelib",   # stdlib GUI
    "webview.platforms.qt", "webview.platforms.gtk",            # non-Windows
    "webview.platforms.cocoa", "webview.platforms.android",     # pywebview
    "webview.platforms.cef",
    "PyQt5", "PyQt6", "PySide2", "PySide6", "gi",               # their deps
    "numpy", "pandas", "matplotlib", "scipy", "PIL",            # never used
    "pytest", "_pytest", "nose", "IPython", "notebook",         # dev only
    "lib2to3", "pydoc_data",

    # The biggest single win, and the one that is not belt-and-braces: without
    # this, site-packages' distutils-precedence.pth drags _distutils_hack and
    # 119 setuptools modules into every build. Nothing here imports setuptools
    # -- requests, bs4, pywebview and pythonnet all read their metadata through
    # importlib.metadata -- so it is a packaging accident, not a dependency.
    #
    # NOT "distutils": PyInstaller's own hook-distutils aliases
    # setuptools._distutils onto that name during analysis, and excluding it
    # makes the build die with 'Target module "distutils" already imported as
    # ExcludedModule'. Dropping setuptools orphans it anyway.
    "setuptools", "_distutils_hack", "pkg_resources",
]


a = Analysis(
    ["app.py"],
    pathex=[str(ROOT)],          # so "fetch_data"/"serve" resolve as top-level
    binaries=[],
    datas=seed_payload(),
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[str(_hook_path)],
    excludes=EXCLUDES,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # UPX off on purpose. It mangles some .NET/native DLLs, and pythonnet's
    # Python.Runtime.dll plus the WebView2 interop libraries are exactly the
    # kind of thing it breaks -- with a failure that only shows up as a window
    # that never opens on someone else's machine.
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,               # GUI app; see the module docstring for the
                                 # logging that makes this safe
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
